name: wifense
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.12
  wifi_flutter: ^0.2.0
  network_info_plus: ^6.1.4
  permission_handler: ^12.0.0  # To handle permissions
  flutter_local_notifications: ^19.1.0 # For notifications
  logger: ^2.5.0   # Add this line for logging
  async: ^2.12.0
  dart_ping: ^9.0.1
  flutter_background_service_android: ^6.3.0
  geolocator: ^14.0.0
  http: ^1.1.0 
  path_provider : ^2.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  android_intent_plus: ^4.0.2
  sqflite: ^2.3.0
  intl: ^0.18.1
  url_launcher: ^6.2.2
  pdf: ^3.10.7
  share_plus: ^7.2.1
  csv: ^6.0.0
  crypto: ^3.0.3
  connectivity_plus: ^6.0.5
  
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints : ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo_dark.png
    - assets/logo_light.png
    - assets/pattern_light.png
    - assets/pattern_dark.png
